// SPDX-FileCopyrightText: 2026 Marcus Baw and Baw Medical Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Fillable input templates derived from a calculator's JSON Schema.
//!
//! `calc <name>` (with no `--input`) prints one of these: a JSON object
//! with every input key present and a placeholder value describing the expected
//! type, allowed values, and meaning. A human or an LLM fills in the values and
//! passes the object straight back via `--input`, so the template's shape is by
//! construction the shape of valid input.
//!
//! The template is generated by walking the schema, so it can never drift from
//! the real contract returned by [`Calculator::input_schema`](crate::Calculator::input_schema).

use serde_json::{Map, Value};

/// Build a fillable input template from a JSON Schema object.
///
/// Each property becomes a key whose placeholder describes the expected value.
/// Nested object properties recurse; every other property becomes a hint string
/// like `"<boolean> Fever in the last 24 hours"` or `"<one of: a|b|c> ..."`.
pub fn template_from_schema(schema: &Value) -> Value {
    let Some(props) = schema.get("properties").and_then(Value::as_object) else {
        return Value::Object(Map::new());
    };
    let mut out = Map::new();
    for (key, prop) in props {
        out.insert(key.clone(), placeholder(prop));
    }
    Value::Object(out)
}

fn placeholder(prop: &Value) -> Value {
    // Nested object: recurse so the template mirrors the structure.
    if prop.get("type").and_then(Value::as_str) == Some("object") {
        return template_from_schema(prop);
    }
    let desc = prop
        .get("description")
        .and_then(Value::as_str)
        .unwrap_or("");
    let kind = type_hint(prop);
    let text = if desc.is_empty() {
        format!("<{kind}>")
    } else {
        format!("<{kind}> {desc}")
    };
    Value::String(text)
}

fn type_hint(prop: &Value) -> String {
    // Enumerated values take priority - they are the most useful hint.
    if let Some(values) = prop.get("enum").and_then(Value::as_array) {
        let opts: Vec<String> = values.iter().map(render_scalar).collect();
        return format!("one of: {}", opts.join("|"));
    }
    match prop.get("type").and_then(Value::as_str) {
        Some("boolean") => "boolean".to_string(),
        Some("integer") => with_range("integer", prop),
        Some("number") => with_range("number", prop),
        Some("string") => "string".to_string(),
        Some("array") => array_hint(prop),
        Some(other) => other.to_string(),
        None => "value".to_string(),
    }
}

fn with_range(base: &str, prop: &Value) -> String {
    let min = prop.get("minimum").and_then(Value::as_i64);
    let max = prop.get("maximum").and_then(Value::as_i64);
    match (min, max) {
        (Some(lo), Some(hi)) => format!("{base} {lo}-{hi}"),
        (Some(lo), None) => format!("{base} >= {lo}"),
        (None, Some(hi)) => format!("{base} <= {hi}"),
        (None, None) => base.to_string(),
    }
}

fn array_hint(prop: &Value) -> String {
    let item_kind = prop
        .get("items")
        .map(type_hint)
        .unwrap_or_else(|| "value".to_string());
    let min = prop.get("minItems").and_then(Value::as_u64);
    let max = prop.get("maxItems").and_then(Value::as_u64);
    match (min, max) {
        (Some(n), Some(m)) if n == m => format!("array of {item_kind} ({n} items)"),
        _ => format!("array of {item_kind}"),
    }
}

fn render_scalar(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn booleans_become_typed_hints() {
        let schema = json!({
            "type": "object",
            "properties": {
                "fever": { "type": "boolean", "description": "Fever in the last 24 hours" }
            }
        });
        let t = template_from_schema(&schema);
        assert_eq!(t["fever"], json!("<boolean> Fever in the last 24 hours"));
    }

    #[test]
    fn enums_list_their_options() {
        let schema = json!({
            "type": "object",
            "properties": {
                "smoking": { "type": "string", "enum": ["non", "ex", "current"], "description": "Smoking status" }
            }
        });
        let t = template_from_schema(&schema);
        assert_eq!(
            t["smoking"],
            json!("<one of: non|ex|current> Smoking status")
        );
    }

    #[test]
    fn arrays_report_item_type_and_count() {
        let schema = json!({
            "type": "object",
            "properties": {
                "responses": {
                    "type": "array",
                    "items": { "type": "integer", "minimum": 0, "maximum": 4 },
                    "minItems": 18, "maxItems": 18,
                    "description": "18 frequency responses"
                }
            }
        });
        let t = template_from_schema(&schema);
        assert_eq!(
            t["responses"],
            json!("<array of integer 0-4 (18 items)> 18 frequency responses")
        );
    }

    #[test]
    fn no_properties_yields_empty_object() {
        assert_eq!(template_from_schema(&json!({"type": "object"})), json!({}));
    }
}
